import { loadEnvironment } from "./load-environment";

async function main(): Promise<void> {
  loadEnvironment();
  const [
    { Client },
    { parseEnv },
    { applyProjectUpdate },
    { projectUpdateSchema },
  ] = await Promise.all([
    import("@notionhq/client"),
    import("../src/config/env"),
    import("../src/services/apply-project-update"),
    import("../src/schemas/project-update"),
  ]);
  const env = parseEnv();
  if (!env.NOTION_TOKEN) throw new Error("NOTION_TOKEN is required");
  const sourceMessageId = `demo-${Date.now()}`;
  const update = projectUpdateSchema.parse({
    submissionSummary: "Demo meeting with Dr. Patel about ultrasound access.",
    contacts: [
      {
        name: "Dr. Maya Patel",
        contactType: "Professor",
        contactStatus: "Contacted",
        organization: "Demo University",
        role: "Ultrasound researcher",
        email: null,
        phone: null,
        website: null,
        expertise: ["Ultrasound"],
        whyRelevant: "Potential equipment collaborator",
        couldHelpWith: ["Equipment access"],
        ownerName: null,
        firstContactDate: null,
        lastContactDate: new Date().toISOString().slice(0, 10),
        nextFollowUp: null,
        discussion: "Possible access to ultrasound equipment",
        outcome: "Requested an equipment list",
        nextStep: "Send equipment list",
        notes: "Demo record",
        sourceMessageId,
        confidence: 1,
      },
    ],
    resources: [],
    tasks: [
      {
        title: "Send equipment list to Dr. Patel",
        type: "Task",
        status: "Not Started",
        assignedToName: null,
        collaboratorNames: [],
        priority: "High",
        dueDate: null,
        startDate: null,
        projectArea: ["Outreach"],
        description: "Send the project equipment list",
        definitionOfDone: "Email delivered",
        relatedContactName: "Dr. Maya Patel",
        relatedResourceUrl: null,
        result: null,
        sourceMessageId,
        confidence: 1,
      },
    ],
    logEntries: [
      {
        title: "Conversation with Dr. Patel",
        date: new Date().toISOString().slice(0, 10),
        entryType: "External Conversation",
        participantNames: [],
        externalParticipantNames: ["Dr. Maya Patel"],
        summary: "Discussed possible ultrasound equipment access.",
        workCompleted: null,
        outcome: "Requested equipment list",
        whatWorked: null,
        whatDidNotWork: null,
        openQuestions: [],
        decisionsMade: [],
        nextSteps: ["Send equipment list"],
        projectPhase: "Outreach",
        originalTranscript: "Demo data generated by seed script.",
        sourceMessageId,
        confidence: 1,
      },
    ],
    uncertainties: [],
    confidence: 1,
    needsConfirmation: false,
  });
  const results = await applyProjectUpdate(
    new Client({ auth: env.NOTION_TOKEN }),
    env,
    update,
  );
  console.log(
    `Created demo data: ${results.map((item) => `${item.kind}:${item.action}`).join(", ")}`,
  );
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
